// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9iuBARr2G0_UduzsEwynehLqw9dsvK4w',
    appId: '1:361124849784:web:b63773db662f99a84f258d',
    messagingSenderId: '361124849784',
    projectId: 'cahs-admin-sheets',
    authDomain: 'cahs-admin-sheets.firebaseapp.com',
    storageBucket: 'cahs-admin-sheets.firebasestorage.app',
    measurementId: 'G-NLFLNNX4J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpBCMhhRIi3sXcw7brTHQzOyroli50iQ',
    appId: '1:361124849784:android:c7538eea8100d8fe4f258d',
    messagingSenderId: '361124849784',
    projectId: 'cahs-admin-sheets',
    storageBucket: 'cahs-admin-sheets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdnYz5y_hj4q6WUpFfs3bgnIEnjEhFXNw',
    appId: '1:361124849784:ios:b603dddc68eebb5f4f258d',
    messagingSenderId: '361124849784',
    projectId: 'cahs-admin-sheets',
    storageBucket: 'cahs-admin-sheets.firebasestorage.app',
    iosBundleId: 'com.example.hsssheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdnYz5y_hj4q6WUpFfs3bgnIEnjEhFXNw',
    appId: '1:361124849784:ios:b603dddc68eebb5f4f258d',
    messagingSenderId: '361124849784',
    projectId: 'cahs-admin-sheets',
    storageBucket: 'cahs-admin-sheets.firebasestorage.app',
    iosBundleId: 'com.example.hsssheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9iuBARr2G0_UduzsEwynehLqw9dsvK4w',
    appId: '1:361124849784:web:7613792fe93b9b734f258d',
    messagingSenderId: '361124849784',
    projectId: 'cahs-admin-sheets',
    authDomain: 'cahs-admin-sheets.firebaseapp.com',
    storageBucket: 'cahs-admin-sheets.firebasestorage.app',
    measurementId: 'G-ELNCCBG4PX',
  );
}
